{"name": "test_login_failed[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'False' == '帐号或密码错'\n  - 帐号或密码错\n  + False", "trace": "self = <TestCases.test_login.TestLogin object at 0x000001E05522EAC8>\ncase = {'check': '帐号或密码错', 'passwd': 'python', 'user': '1868472055'}\nback_login = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"4312aa878099b509a27cdda0f83158dc\")>\n\n    @pytest.mark.parametrize(\"case\", td.invalid_data)\n    def test_login_failed(self, case, back_login):\n        LoginPage(back_login).login(case[\"user\"], case[\"passwd\"])\n        res = LoginPage(back_login).get_error_msg_from_login_area()\n        LoginPage(back_login).close_login_window()\n>       assert res == case['check']\nE       AssertionError: assert 'False' == '帐号或密码错'\nE         - 帐号或密码错\nE         + False\n\nTestCases\\test_login.py:16: AssertionError"}, "attachments": [{"name": "失败截图", "source": "4758b2f4-036c-4f86-ab79-990dc4122d43-attachment.png", "type": "image/png"}, {"name": "失败截图", "source": "f7ab4e5d-b441-4591-82b4-e9188aeca53f-attachment.png", "type": "image/png"}], "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '帐号或密码错'}"}], "start": 1642155512894, "stop": 1642155534431, "uuid": "6956ed09-02aa-4bd0-8c38-87decc908151", "historyId": "73a882954a57ef1fcc4da4b1bd031951", "testCaseId": "76d8a45a420a86cfad6f84d07a44a7e3", "fullName": "TestCases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "11036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}