{"name": "test_login_failed[case2]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('url', <SubRequest 'init' for <Function test_login_failed[case2]>>)", "trace": "file D:\\Test_framework\\Web_auto\\TestCases\\test_login.py, line 11\n      @pytest.mark.parametrize(\"case\", td.invalid_data)\n      def test_login_failed(self, case, back_login):\nfile D:\\Test_framework\\Web_auto\\TestCases\\conftest.py, line 38\n  @pytest.fixture(scope=\"class\")\n  def back_login(init):\nfile D:\\Test_framework\\Web_auto\\TestCases\\conftest.py, line 28\n  @pytest.fixture(scope=\"class\")\n  def init(url):\nE       fixture 'url' not found\n>       available fixtures: back_login, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, init, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\Test_framework\\Web_auto\\TestCases\\conftest.py:28"}, "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '帐号或密码错'}"}], "start": 1647847718722, "stop": 1647847718722, "uuid": "2644f423-ebe9-4ec8-879e-3324a96277c9", "historyId": "73a882954a57ef1fcc4da4b1bd031951", "testCaseId": "76d8a45a420a86cfad6f84d07a44a7e3", "fullName": "TestCases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "19632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}