{"name": "test_login_failed[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'False' == '帐号或密码错'\n  - 帐号或密码错\n  + False", "trace": "self = <TestCases.test_login1.TestLogin object at 0x000001F50E2E8608>\ncase = {'check': '帐号或密码错', 'passwd': 'python', 'user': '1868472055'}\nback_login = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ebaccf51e054a0fd78865a4dc2cfe8d1\")>\n\n    @pytest.mark.parametrize(\"case\", td.invalid_data)\n    def test_login_failed(self, case, back_login):\n        LoginPage(back_login).login(case[\"user\"], case[\"passwd\"])\n        res = LoginPage(back_login).get_error_msg_from_login_area()\n        LoginPage(back_login).close_login_window()\n>       assert res == case['check']\nE       AssertionError: assert 'False' == '帐号或密码错'\nE         - 帐号或密码错\nE         + False\n\nTestCases\\test_login1.py:16: AssertionError"}, "attachments": [{"name": "失败截图", "source": "b23248d0-f267-43b8-95e1-f88755b99108-attachment.png", "type": "image/png"}, {"name": "失败截图", "source": "69da982a-d5e5-4fb7-8bf7-199ffa1cba04-attachment.png", "type": "image/png"}], "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '帐号或密码错'}"}], "start": 1647848796575, "stop": 1647848818482, "uuid": "a9acaf86-676c-4d94-82d8-efb2a255f70b", "historyId": "1bd1937941fff8809d36a7e206d429da", "testCaseId": "6d230ca66b6dfc3f741b1dec342650f6", "fullName": "TestCases.test_login1.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login1"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "19664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login1"}]}