{"name": "test_login_failed[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'False' == '帐号或密码错'\n  - 帐号或密码错\n  + False", "trace": "self = <TestCases.test_login.TestLogin object at 0x0000024F3BB21B48>\ncase = {'check': '帐号或密码错', 'passwd': 'python', 'user': '1868472055'}\nback_login = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"22aa5bda87ef056515ebbd3454f8be4d\")>\n\n    @pytest.mark.parametrize(\"case\", td.invalid_data)\n    def test_login_failed(self, case, back_login):\n        LoginPage(back_login).login(case[\"user\"], case[\"passwd\"])\n        res = LoginPage(back_login).get_error_msg_from_login_area()\n        LoginPage(back_login).close_login_window()\n>       assert res == case['check']\nE       AssertionError: assert 'False' == '帐号或密码错'\nE         - 帐号或密码错\nE         + False\n\nTestCases\\test_login.py:16: AssertionError"}, "attachments": [{"name": "失败截图", "source": "dd8974ec-2324-4c78-9dde-c0ae25b8aa24-attachment.png", "type": "image/png"}, {"name": "失败截图", "source": "1e5dd4b1-3c5c-442a-bc3f-63970bf8f27d-attachment.png", "type": "image/png"}], "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '帐号或密码错'}"}], "start": 1647508273811, "stop": 1647508296783, "uuid": "b1acf594-9859-4174-9532-a6daac1b8d28", "historyId": "73a882954a57ef1fcc4da4b1bd031951", "testCaseId": "76d8a45a420a86cfad6f84d07a44a7e3", "fullName": "TestCases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_login')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "81660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}