{"name": "test_login_failed[case2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'False' == '帐号或密码错'\n  - 帐号或密码错\n  + False", "trace": "self = <TestCases.test_login.TestLogin object at 0x0000023F8D3D4588>\ncase = {'check': '帐号或密码错', 'passwd': 'python', 'user': '1868472055'}\ninit = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b2bb4000f6f5902a624899848bd34f7f\")>\n\n    @pytest.mark.parametrize(\"case\", td.invalid_data)\n    def test_login_failed(self, case, init):\n        LoginPage(init).login(case[\"user\"], case[\"passwd\"])\n        res = LoginPage(init).get_error_msg_from_login_area()\n        LoginPage(init).close_login_window()\n>       assert res == case['check']\nE       AssertionError: assert 'False' == '帐号或密码错'\nE         - 帐号或密码错\nE         + False\n\nTestCases\\test_login.py:16: AssertionError"}, "attachments": [{"name": "失败截图", "source": "39405776-2f4b-4f10-96b1-7e502f0b4d7b-attachment.png", "type": "image/png"}, {"name": "失败截图", "source": "b0551b7c-2488-44b7-b90e-992dc2e70c0f-attachment.png", "type": "image/png"}], "parameters": [{"name": "case", "value": "{'user': '1868472055', 'passwd': 'python', 'check': '帐号或密码错'}"}], "start": 1647848658070, "stop": 1647848679873, "uuid": "4aadc390-8314-4484-82ef-63a35db221d1", "historyId": "73a882954a57ef1fcc4da4b1bd031951", "testCaseId": "76d8a45a420a86cfad6f84d07a44a7e3", "fullName": "TestCases.test_login.TestLogin#test_login_failed", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-AWORNJEVXPKP"}, {"name": "thread", "value": "17048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}